#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MonetaryBank")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DataBase.Properties.Settings.Default.MonetaryBankConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CPF;
		
		private string _NumeroConta;
		
		private string _Nome;
		
		private char _Sexo;
		
		private string _RG;
		
		private string _Email;
		
		private string _Nascimento;
		
		private string _Telefone;
		
		private string _NomeMae;
		
		private System.Nullable<bool> _NaoConstaMae;
		
		private string _NomePai;
		
		private System.Nullable<bool> _NaoConstaPai;
		
		private string _CEP;
		
		private string _Rua;
		
		private string _Numero;
		
		private string _Complemento;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _Estado;
		
		private string _Carteira;
		
		private string _Profissao;
		
		private decimal _Renda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnNumeroContaChanging(string value);
    partial void OnNumeroContaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnSexoChanging(char value);
    partial void OnSexoChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNascimentoChanging(string value);
    partial void OnNascimentoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnNomeMaeChanging(string value);
    partial void OnNomeMaeChanged();
    partial void OnNaoConstaMaeChanging(System.Nullable<bool> value);
    partial void OnNaoConstaMaeChanged();
    partial void OnNomePaiChanging(string value);
    partial void OnNomePaiChanged();
    partial void OnNaoConstaPaiChanging(System.Nullable<bool> value);
    partial void OnNaoConstaPaiChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnRuaChanging(string value);
    partial void OnRuaChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnComplementoChanging(string value);
    partial void OnComplementoChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnCarteiraChanging(string value);
    partial void OnCarteiraChanged();
    partial void OnProfissaoChanging(string value);
    partial void OnProfissaoChanged();
    partial void OnRendaChanging(decimal value);
    partial void OnRendaChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConta", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string NumeroConta
		{
			get
			{
				return this._NumeroConta;
			}
			set
			{
				if ((this._NumeroConta != value))
				{
					this.OnNumeroContaChanging(value);
					this.SendPropertyChanging();
					this._NumeroConta = value;
					this.SendPropertyChanged("NumeroConta");
					this.OnNumeroContaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1) NOT NULL")]
		public char Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nascimento", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Nascimento
		{
			get
			{
				return this._Nascimento;
			}
			set
			{
				if ((this._Nascimento != value))
				{
					this.OnNascimentoChanging(value);
					this.SendPropertyChanging();
					this._Nascimento = value;
					this.SendPropertyChanged("Nascimento");
					this.OnNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeMae", DbType="VarChar(100)")]
		public string NomeMae
		{
			get
			{
				return this._NomeMae;
			}
			set
			{
				if ((this._NomeMae != value))
				{
					this.OnNomeMaeChanging(value);
					this.SendPropertyChanging();
					this._NomeMae = value;
					this.SendPropertyChanged("NomeMae");
					this.OnNomeMaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NaoConstaMae", DbType="Bit")]
		public System.Nullable<bool> NaoConstaMae
		{
			get
			{
				return this._NaoConstaMae;
			}
			set
			{
				if ((this._NaoConstaMae != value))
				{
					this.OnNaoConstaMaeChanging(value);
					this.SendPropertyChanging();
					this._NaoConstaMae = value;
					this.SendPropertyChanged("NaoConstaMae");
					this.OnNaoConstaMaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePai", DbType="VarChar(100)")]
		public string NomePai
		{
			get
			{
				return this._NomePai;
			}
			set
			{
				if ((this._NomePai != value))
				{
					this.OnNomePaiChanging(value);
					this.SendPropertyChanging();
					this._NomePai = value;
					this.SendPropertyChanged("NomePai");
					this.OnNomePaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NaoConstaPai", DbType="Bit")]
		public System.Nullable<bool> NaoConstaPai
		{
			get
			{
				return this._NaoConstaPai;
			}
			set
			{
				if ((this._NaoConstaPai != value))
				{
					this.OnNaoConstaPaiChanging(value);
					this.SendPropertyChanging();
					this._NaoConstaPai = value;
					this.SendPropertyChanged("NaoConstaPai");
					this.OnNaoConstaPaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rua", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Rua
		{
			get
			{
				return this._Rua;
			}
			set
			{
				if ((this._Rua != value))
				{
					this.OnRuaChanging(value);
					this.SendPropertyChanging();
					this._Rua = value;
					this.SendPropertyChanged("Rua");
					this.OnRuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Complemento
		{
			get
			{
				return this._Complemento;
			}
			set
			{
				if ((this._Complemento != value))
				{
					this.OnComplementoChanging(value);
					this.SendPropertyChanging();
					this._Complemento = value;
					this.SendPropertyChanged("Complemento");
					this.OnComplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carteira", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Carteira
		{
			get
			{
				return this._Carteira;
			}
			set
			{
				if ((this._Carteira != value))
				{
					this.OnCarteiraChanging(value);
					this.SendPropertyChanging();
					this._Carteira = value;
					this.SendPropertyChanged("Carteira");
					this.OnCarteiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profissao", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Profissao
		{
			get
			{
				return this._Profissao;
			}
			set
			{
				if ((this._Profissao != value))
				{
					this.OnProfissaoChanging(value);
					this.SendPropertyChanging();
					this._Profissao = value;
					this.SendPropertyChanged("Profissao");
					this.OnProfissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renda", DbType="Money NOT NULL")]
		public decimal Renda
		{
			get
			{
				return this._Renda;
			}
			set
			{
				if ((this._Renda != value))
				{
					this.OnRendaChanging(value);
					this.SendPropertyChanging();
					this._Renda = value;
					this.SendPropertyChanged("Renda");
					this.OnRendaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
